# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "mvanbeusekom"
    labels:
      - "platform: ci"

  - package-ecosystem: "gradle"
    directory: "/geocoding_android/android"
    commit-message:
      prefix: "[geocoding_android]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "com.android.tools.build:gradle"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "junit:junit"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "org.mockito:*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "androidx.test:*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "gradle"
    directory: "/geocoding_android/example/android/app"
    commit-message:
      prefix: "[geocoding_android]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "gradle"
    directory: "/geocoding/example/android/app"
    commit-message:
      prefix: "[geolocator]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

  - package-ecosystem: "pub"
    directory: "/geocoding"
    commit-message:
      prefix: "[geocoding]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10
    
  - package-ecosystem: "pub"
    directory: "/geocoding/example"
    commit-message:
      prefix: "[geocoding]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10

  - package-ecosystem: "pub"
    directory: "/geocoding_android"
    commit-message:
      prefix: "[geocoding_android]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10
    
  - package-ecosystem: "pub"
    directory: "/geocoding_android/example"
    commit-message:
      prefix: "[geocoding_android]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10

  - package-ecosystem: "pub"
    directory: "/geocoding_darwin"
    commit-message:
      prefix: "[geocoding_darwin]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10
    
  - package-ecosystem: "pub"
    directory: "/geocoding_darwin/example"
    commit-message:
      prefix: "[geocoding_darwin]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10

  - package-ecosystem: "pub"
    directory: "/geocoding_platform_interface"
    commit-message:
      prefix: "[geocoding_platform_interface]"
    schedule:
      interval: "weekly"
    reviewers:
      - "mvanbeusekom"
    open-pull-requests-limit: 10
