// Mocks generated by Mockito 5.4.4 from annotations
// in geocoding_platform_interface/test/src/geocoding_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:geocoding_platform_interface/src/geocoding.dart' as _i2;
import 'package:geocoding_platform_interface/src/geocoding_platform_factory.dart'
    as _i3;
import 'package:geocoding_platform_interface/src/types/types.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGeocoding_0 extends _i1.SmartFake implements _i2.Geocoding {
  _FakeGeocoding_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GeocodingPlatformFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeocodingPlatformFactory extends _i1.Mock
    implements _i3.GeocodingPlatformFactory {
  @override
  _i2.Geocoding createGeocoding(_i4.GeocodingCreationParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#createGeocoding, [params]),
            returnValue: _FakeGeocoding_0(
              this,
              Invocation.method(#createGeocoding, [params]),
            ),
            returnValueForMissingStub: _FakeGeocoding_0(
              this,
              Invocation.method(#createGeocoding, [params]),
            ),
          )
          as _i2.Geocoding);
}
