name: geocoding_ios
description: A Flutter Geocoding plugin which provides easy geocoding and reverse-geocoding features.
version: 3.0.2
repository: https://github.com/baseflow/flutter-geocoding/tree/main/geocoding_ios
issue_tracker: https://github.com/Baseflow/flutter-geocoding/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter

  geocoding_platform_interface:
    path: ../geocoding_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    implements: geocoding
    platforms:
      ios:
        pluginClass: GeocodingPlugin
        dartPluginClass: GeocodingIOS
