// Autogenerated from Pigeon (v26.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.baseflow.geocoding

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object AndroidGeocoderLibraryPigeonUtils {

  fun createConnectionError(channelName: String): AndroidGeocoderError {
    return AndroidGeocoderError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is AndroidGeocoderError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class AndroidGeocoderError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()
/**
 * Maintains instances used to communicate with the corresponding objects in Dart.
 *
 * Objects stored in this container are represented by an object in Dart that is also stored in
 * an InstanceManager with the same identifier.
 *
 * When an instance is added with an identifier, either can be used to retrieve the other.
 *
 * Added instances are added as a weak reference and a strong reference. When the strong
 * reference is removed with [remove] and the weak reference is deallocated, the
 * `finalizationListener.onFinalize` is called with the instance's identifier. However, if the strong
 * reference is removed and then the identifier is retrieved with the intention to pass the identifier
 * to Dart (e.g. calling [getIdentifierForStrongReference]), the strong reference to the instance
 * is recreated. The strong reference will then need to be removed manually again.
 */
@Suppress("UNCHECKED_CAST", "MemberVisibilityCanBePrivate")
class AndroidGeocoderLibraryPigeonInstanceManager(private val finalizationListener: PigeonFinalizationListener) {
  /** Interface for listening when a weak reference of an instance is removed from the manager.  */
  interface PigeonFinalizationListener {
    fun onFinalize(identifier: Long)
  }

  // Extends WeakReference and overrides the `equals` and `hashCode` methods using identity rather
  // than equality.
  //
  // Two `IdentityWeakReference`s are equal if either
  // 1: `get()` returns the identical nonnull value for both references.
  // 2: `get()` returns null for both references and the references are identical.
  class IdentityWeakReference<T : Any> : java.lang.ref.WeakReference<T> {
    private val savedHashCode: Int

    constructor(instance: T) : this(instance, null)

    constructor(instance: T, queue: java.lang.ref.ReferenceQueue<T>?) : super(instance, queue) {
      savedHashCode = System.identityHashCode(instance)
    }

    override fun equals(other: Any?): Boolean {
      val instance = get()
      if (instance != null) {
        return other is IdentityWeakReference<*> && other.get() === instance
      }
      return other === this
    }

    override fun hashCode(): Int {
      return savedHashCode
    }
  }

  private val identifiers = java.util.WeakHashMap<IdentityWeakReference<Any>, Long>()
  private val weakInstances = HashMap<Long, IdentityWeakReference<Any>>()
  private val strongInstances = HashMap<Long, Any>()
  private val referenceQueue = java.lang.ref.ReferenceQueue<Any>()
  private val weakReferencesToIdentifiers = HashMap<IdentityWeakReference<Any>, Long>()
  private val handler = android.os.Handler(android.os.Looper.getMainLooper())
  private val releaseAllFinalizedInstancesRunnable = Runnable {
    this.releaseAllFinalizedInstances()
  }
  private var nextIdentifier: Long = minHostCreatedIdentifier
  private var hasFinalizationListenerStopped = false

  /**
   * Modifies the time interval used to define how often this instance removes garbage collected
   * weak references to native Android objects that this instance was managing.
   */
  var clearFinalizedWeakReferencesInterval: Long = 3000
    set(value) {
      handler.removeCallbacks(releaseAllFinalizedInstancesRunnable)
      field = value
      releaseAllFinalizedInstances()
    }

  init {
    handler.postDelayed(releaseAllFinalizedInstancesRunnable, clearFinalizedWeakReferencesInterval)
  }

  companion object {
    // Identifiers are locked to a specific range to avoid collisions with objects
    // created simultaneously from Dart.
    // Host uses identifiers >= 2^16 and Dart is expected to use values n where,
    // 0 <= n < 2^16.
    private const val minHostCreatedIdentifier: Long = 65536
    private const val tag = "PigeonInstanceManager"

    /**
     * Instantiate a new manager with a listener for garbage collected weak
     * references.
     *
     * When the manager is no longer needed, [stopFinalizationListener] must be called.
     */
    fun create(finalizationListener: PigeonFinalizationListener): AndroidGeocoderLibraryPigeonInstanceManager {
      return AndroidGeocoderLibraryPigeonInstanceManager(finalizationListener)
    }
  }

  /**
   * Removes `identifier` and return its associated strongly referenced instance, if present,
   * from the manager.
   */
  fun <T> remove(identifier: Long): T? {
    logWarningIfFinalizationListenerHasStopped()
    return strongInstances.remove(identifier) as T?
  }

  /**
   * Retrieves the identifier paired with an instance, if present, otherwise `null`.
   *
   *
   * If the manager contains a strong reference to `instance`, it will return the identifier
   * associated with `instance`. If the manager contains only a weak reference to `instance`, a new
   * strong reference to `instance` will be added and will need to be removed again with [remove].
   *
   *
   * If this method returns a nonnull identifier, this method also expects the Dart
   * `AndroidGeocoderLibraryPigeonInstanceManager` to have, or recreate, a weak reference to the Dart instance the
   * identifier is associated with.
   */
  fun getIdentifierForStrongReference(instance: Any?): Long? {
    logWarningIfFinalizationListenerHasStopped()
    if (instance == null) {
      return null
    }
    val identifier = identifiers[IdentityWeakReference(instance)]
    if (identifier != null) {
      strongInstances[identifier] = instance
    }
    return identifier
  }

  /**
   * Adds a new instance that was instantiated from Dart.
   *
   * The same instance can be added multiple times, but each identifier must be unique. This
   * allows two objects that are equivalent (e.g. the `equals` method returns true and their
   * hashcodes are equal) to both be added.
   *
   * [identifier] must be >= 0 and unique.
   */
  fun addDartCreatedInstance(instance: Any, identifier: Long) {
    logWarningIfFinalizationListenerHasStopped()
    addInstance(instance, identifier)
  }

  /**
   * Adds a new unique instance that was instantiated from the host platform.
   *
   * If the manager contains [instance], this returns the corresponding identifier. If the
   * manager does not contain [instance], this adds the instance and returns a unique
   * identifier for that [instance].
   */
  fun addHostCreatedInstance(instance: Any): Long {
    logWarningIfFinalizationListenerHasStopped()
    require(!containsInstance(instance)) { "Instance of ${instance.javaClass} has already been added." }
    val identifier = nextIdentifier++
    addInstance(instance, identifier)
    return identifier
  }

  /** Retrieves the instance associated with identifier, if present, otherwise `null`. */
  fun <T : Any> getInstance(identifier: Long): T? {
    logWarningIfFinalizationListenerHasStopped()
    val instance = weakInstances[identifier] as IdentityWeakReference<T>?
    return instance?.get()
  }

  /** Returns whether this manager contains the given `instance`. */
  fun containsInstance(instance: Any?): Boolean {
    logWarningIfFinalizationListenerHasStopped()
    return instance != null && identifiers.containsKey(IdentityWeakReference(instance))
  }

  /**
   * Stops the periodic run of the [PigeonFinalizationListener] for instances that have been garbage
   * collected.
   *
   * The InstanceManager can continue to be used, but the [PigeonFinalizationListener] will no
   * longer be called and methods will log a warning.
   */
  fun stopFinalizationListener() {
    handler.removeCallbacks(releaseAllFinalizedInstancesRunnable)
    hasFinalizationListenerStopped = true
  }

  /**
   * Removes all of the instances from this manager.
   *
   * The manager will be empty after this call returns.
   */
  fun clear() {
    identifiers.clear()
    weakInstances.clear()
    strongInstances.clear()
    weakReferencesToIdentifiers.clear()
  }

  /**
   * Whether the [PigeonFinalizationListener] is still being called for instances that are garbage
   * collected.
   *
   * See [stopFinalizationListener].
   */
  fun hasFinalizationListenerStopped(): Boolean {
    return hasFinalizationListenerStopped
  }

  private fun releaseAllFinalizedInstances() {
    if (hasFinalizationListenerStopped()) {
      return
    }
    var reference: IdentityWeakReference<Any>?
    while ((referenceQueue.poll() as IdentityWeakReference<Any>?).also { reference = it } != null) {
      val identifier = weakReferencesToIdentifiers.remove(reference)
      if (identifier != null) {
        weakInstances.remove(identifier)
        strongInstances.remove(identifier)
        finalizationListener.onFinalize(identifier)
      }
    }
    handler.postDelayed(releaseAllFinalizedInstancesRunnable, clearFinalizedWeakReferencesInterval)
  }

  private fun addInstance(instance: Any, identifier: Long) {
    require(identifier >= 0) { "Identifier must be >= 0: $identifier" }
    require(!weakInstances.containsKey(identifier)) {
      "Identifier has already been added: $identifier"
    }
    val weakReference = IdentityWeakReference(instance, referenceQueue)
    identifiers[weakReference] = identifier
    weakInstances[identifier] = weakReference
    weakReferencesToIdentifiers[weakReference] = identifier
    strongInstances[identifier] = instance
  }

  private fun logWarningIfFinalizationListenerHasStopped() {
    if (hasFinalizationListenerStopped()) {
      Log.w(
        tag,
        "The manager was used after calls to the PigeonFinalizationListener has been stopped."
      )
    }
  }
}


/** Generated API for managing the Dart and native `InstanceManager`s. */
private class AndroidGeocoderLibraryPigeonInstanceManagerApi(val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by AndroidGeocoderLibraryPigeonInstanceManagerApi. */
    val codec: MessageCodec<Any?> by lazy {
      AndroidGeocoderLibraryPigeonCodec()
    }

    /**
     * Sets up an instance of `AndroidGeocoderLibraryPigeonInstanceManagerApi` to handle messages from the
     * `binaryMessenger`.
     */
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, instanceManager: AndroidGeocoderLibraryPigeonInstanceManager?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.PigeonInternalInstanceManager.removeStrongReference", codec)
        if (instanceManager != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val identifierArg = args[0] as Long
            val wrapped: List<Any?> = try {
              instanceManager.remove<Any?>(identifierArg)
              listOf(null)
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.PigeonInternalInstanceManager.clear", codec)
        if (instanceManager != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              instanceManager.clear()
              listOf(null)
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  fun removeStrongReference(identifierArg: Long, callback: (Result<Unit>) -> Unit)
{
    val channelName = "dev.flutter.pigeon.geocoding_android.PigeonInternalInstanceManager.removeStrongReference"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(identifierArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(AndroidGeocoderError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(AndroidGeocoderLibraryPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
/**
 * Provides implementations for each ProxyApi implementation and provides access to resources
 * needed by any implementation.
 */
abstract class AndroidGeocoderLibraryPigeonProxyApiRegistrar(val binaryMessenger: BinaryMessenger) {
  /** Whether APIs should ignore calling to Dart. */
  public var ignoreCallsToDart = false
  val instanceManager: AndroidGeocoderLibraryPigeonInstanceManager
  private var _codec: MessageCodec<Any?>? = null
  val codec: MessageCodec<Any?>
    get() {
      if (_codec == null) {
        _codec = AndroidGeocoderLibraryPigeonProxyApiBaseCodec(this)
      }
      return _codec!!
    }

  init {
    val api = AndroidGeocoderLibraryPigeonInstanceManagerApi(binaryMessenger)
    instanceManager = AndroidGeocoderLibraryPigeonInstanceManager.create(
      object : AndroidGeocoderLibraryPigeonInstanceManager.PigeonFinalizationListener {
        override fun onFinalize(identifier: Long) {
          api.removeStrongReference(identifier) {
            if (it.isFailure) {
              Log.e(
                "PigeonProxyApiRegistrar",
                "Failed to remove Dart strong reference with identifier: $identifier"
              )
            }
          }
        }
      }
    )
  }
  /**
   * An implementation of [PigeonApiAddress] used to add a new Dart instance of
   * `Address` to the Dart `InstanceManager`.
   */
  abstract fun getPigeonApiAddress(): PigeonApiAddress

  /**
   * An implementation of [PigeonApiGeographicBounds] used to add a new Dart instance of
   * `GeographicBounds` to the Dart `InstanceManager`.
   */
  abstract fun getPigeonApiGeographicBounds(): PigeonApiGeographicBounds

  /**
   * An implementation of [PigeonApiBuild] used to add a new Dart instance of
   * `Build` to the Dart `InstanceManager`.
   */
  abstract fun getPigeonApiBuild(): PigeonApiBuild

  /**
   * An implementation of [PigeonApiGeocodeListener] used to add a new Dart instance of
   * `GeocodeListener` to the Dart `InstanceManager`.
   */
  abstract fun getPigeonApiGeocodeListener(): PigeonApiGeocodeListener

  /**
   * An implementation of [PigeonApiGeocoder] used to add a new Dart instance of
   * `Geocoder` to the Dart `InstanceManager`.
   */
  abstract fun getPigeonApiGeocoder(): PigeonApiGeocoder

  /**
   * An implementation of [PigeonApiLocale] used to add a new Dart instance of
   * `Locale` to the Dart `InstanceManager`.
   */
  abstract fun getPigeonApiLocale(): PigeonApiLocale

  fun setUp() {
    AndroidGeocoderLibraryPigeonInstanceManagerApi.setUpMessageHandlers(binaryMessenger, instanceManager)
    PigeonApiAddress.setUpMessageHandlers(binaryMessenger, getPigeonApiAddress())
    PigeonApiGeographicBounds.setUpMessageHandlers(binaryMessenger, getPigeonApiGeographicBounds())
    PigeonApiBuild.setUpMessageHandlers(binaryMessenger, getPigeonApiBuild())
    PigeonApiGeocodeListener.setUpMessageHandlers(binaryMessenger, getPigeonApiGeocodeListener())
    PigeonApiGeocoder.setUpMessageHandlers(binaryMessenger, getPigeonApiGeocoder())
    PigeonApiLocale.setUpMessageHandlers(binaryMessenger, getPigeonApiLocale())
  }
  fun tearDown() {
    AndroidGeocoderLibraryPigeonInstanceManagerApi.setUpMessageHandlers(binaryMessenger, null)
    PigeonApiAddress.setUpMessageHandlers(binaryMessenger, null)
    PigeonApiGeographicBounds.setUpMessageHandlers(binaryMessenger, null)
    PigeonApiBuild.setUpMessageHandlers(binaryMessenger, null)
    PigeonApiGeocodeListener.setUpMessageHandlers(binaryMessenger, null)
    PigeonApiGeocoder.setUpMessageHandlers(binaryMessenger, null)
    PigeonApiLocale.setUpMessageHandlers(binaryMessenger, null)
  }
}
private class AndroidGeocoderLibraryPigeonProxyApiBaseCodec(val registrar: AndroidGeocoderLibraryPigeonProxyApiRegistrar) : AndroidGeocoderLibraryPigeonCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        val identifier: Long = readValue(buffer) as Long
        val instance: Any? = registrar.instanceManager.getInstance(identifier)
        if (instance == null) {
          Log.e(
            "PigeonProxyApiBaseCodec",
            "Failed to find instance with identifier: $identifier"
          )
        }
        return instance
      }
      else -> super.readValueOfType(type, buffer)
    }
  }

  override fun writeValue(stream: ByteArrayOutputStream, value: Any?) {
    if (value is Boolean || value is ByteArray || value is Double || value is DoubleArray || value is FloatArray || value is Int || value is IntArray || value is List<*> || value is Long || value is LongArray || value is Map<*, *> || value is String || value == null) {
      super.writeValue(stream, value)
      return
    }

    fun logNewInstanceFailure(apiName: String, value: Any, exception: Throwable?) {
      Log.w(
        "PigeonProxyApiBaseCodec",
        "Failed to create new Dart proxy instance of $apiName: $value. $exception"
      )
    }

    if (value is android.location.Address) {
      registrar.getPigeonApiAddress().pigeon_newInstance(value) {
        if (it.isFailure) {
          logNewInstanceFailure("Address", value, it.exceptionOrNull())
        }
      }
    }
     else if (value is GeographicBounds) {
      registrar.getPigeonApiGeographicBounds().pigeon_newInstance(value) {
        if (it.isFailure) {
          logNewInstanceFailure("GeographicBounds", value, it.exceptionOrNull())
        }
      }
    }
     else if (value is android.os.Build) {
      registrar.getPigeonApiBuild().pigeon_newInstance(value) {
        if (it.isFailure) {
          logNewInstanceFailure("Build", value, it.exceptionOrNull())
        }
      }
    }
     else if (android.os.Build.VERSION.SDK_INT >= 33 && value is android.location.Geocoder.GeocodeListener) {
      registrar.getPigeonApiGeocodeListener().pigeon_newInstance(value) {
        if (it.isFailure) {
          logNewInstanceFailure("GeocodeListener", value, it.exceptionOrNull())
        }
      }
    }
     else if (value is android.location.Geocoder) {
      registrar.getPigeonApiGeocoder().pigeon_newInstance(value) {
        if (it.isFailure) {
          logNewInstanceFailure("Geocoder", value, it.exceptionOrNull())
        }
      }
    }
     else if (value is java.util.Locale) {
      registrar.getPigeonApiLocale().pigeon_newInstance(value) {
        if (it.isFailure) {
          logNewInstanceFailure("Locale", value, it.exceptionOrNull())
        }
      }
    }

    when {
      registrar.instanceManager.containsInstance(value) -> {
        stream.write(128)
        writeValue(stream, registrar.instanceManager.getIdentifierForStrongReference(value))
      }
      else -> throw IllegalArgumentException("Unsupported value: '$value' of type '${value.javaClass.name}'")
    }
  }
}
private open class AndroidGeocoderLibraryPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}

/**
 * A class representing an Address, that is, a set of Strings describing a
 * location.
 *
 * See https://developer.android.com/reference/android/location/Address.
 */
@Suppress("UNCHECKED_CAST")
abstract class PigeonApiAddress(open val pigeonRegistrar: AndroidGeocoderLibraryPigeonProxyApiRegistrar) {
  /**
   * Returns a line of the address numbered by the given index (starting at 0),
   * or null if no such line is present.
   */
  abstract fun getAddressLine(pigeon_instance: android.location.Address, index: Long): String?

  /**
   * Returns the administrative area name of the address, for example, "CA", or
   * null if it is unknown/
   */
  abstract fun getAdminArea(pigeon_instance: android.location.Address): String?

  /**
   * Returns the country code of the address, for example "US", or null if it
   * is unknown.
   */
  abstract fun getCountryCode(pigeon_instance: android.location.Address): String?

  /**
   * Returns the localized country name of the address, for example "Iceland",
   * or null if it is unknown.
   */
  abstract fun getCountryName(pigeon_instance: android.location.Address): String?

  /**
   * Returns the feature name of the address, for example, "Golden Gate Bridge",
   * or null if it is unknown
   */
  abstract fun getFeatureName(pigeon_instance: android.location.Address): String?

  /** Returns the latitude of the address if known. */
  abstract fun getLatitude(pigeon_instance: android.location.Address): Double?

  /** Returns the Locale associated with this address. */
  abstract fun getLocale(pigeon_instance: android.location.Address): java.util.Locale

  /**
   * Returns the locality of the address, for example "Mountain View", or null
   * if it is unknown.
   */
  abstract fun getLocality(pigeon_instance: android.location.Address): String?

  /** Returns the longitude of the address if known. */
  abstract fun getLongitude(pigeon_instance: android.location.Address): Double?

  /** Returns the largest index currently in use to specify an address line. */
  abstract fun getMaxAddressLineIndex(pigeon_instance: android.location.Address): Long

  /**
   * Returns the phone number of the address if known, or null if it is
   * unknown.
   */
  abstract fun getPhone(pigeon_instance: android.location.Address): String?

  /**
   * Returns the postal code of the address, for example "94110", or null if it
   * is unknown.
   */
  abstract fun getPostalCode(pigeon_instance: android.location.Address): String?

  /** Returns the premises of the address, or null if it is unknown. */
  abstract fun getPremises(pigeon_instance: android.location.Address): String?

  /**
   * Returns the sub-administrative area name of the address, for example,
   * "Santa Clara County", or null if it is unknown
   */
  abstract fun getSubAdminArea(pigeon_instance: android.location.Address): String?

  /** Returns the sub-locality of the address, or null if it is unknown. */
  abstract fun getSubLocality(pigeon_instance: android.location.Address): String?

  /** Returns the sub-thoroughfare name of the address, which may be null. */
  abstract fun getSubThouroughfare(pigeon_instance: android.location.Address): String?

  /**
   * Returns the thoroughfare name of the address, for example,
   * "1600 Ampitheater Parkway", which may be null
   */
  abstract fun getThouroughfare(pigeon_instance: android.location.Address): String?

  /** Returns the public URL for the address if known, or null if it is unknown. */
  abstract fun getUrl(pigeon_instance: android.location.Address): String?

  /**
   * Returns true if a latitude has been assigned to this Address, false
   * otherwise.
   */
  abstract fun hasLatitude(pigeon_instance: android.location.Address): Boolean

  /**
   * Returns true if a longitude has been assigned to this Address, false
   * otherwise.
   */
  abstract fun hasLongitude(pigeon_instance: android.location.Address): Boolean

  companion object {
    @Suppress("LocalVariableName")
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, api: PigeonApiAddress?) {
      val codec = api?.pigeonRegistrar?.codec ?: AndroidGeocoderLibraryPigeonCodec()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Address.getAddressLine", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.location.Address
            val indexArg = args[1] as Long
            val wrapped: List<Any?> = try {
              listOf(api.getAddressLine(pigeon_instanceArg, indexArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Address.getAdminArea", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.location.Address
            val wrapped: List<Any?> = try {
              listOf(api.getAdminArea(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Address.getCountryCode", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.location.Address
            val wrapped: List<Any?> = try {
              listOf(api.getCountryCode(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Address.getCountryName", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.location.Address
            val wrapped: List<Any?> = try {
              listOf(api.getCountryName(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Address.getFeatureName", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.location.Address
            val wrapped: List<Any?> = try {
              listOf(api.getFeatureName(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Address.getLatitude", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.location.Address
            val wrapped: List<Any?> = try {
              listOf(api.getLatitude(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Address.getLocale", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.location.Address
            val wrapped: List<Any?> = try {
              listOf(api.getLocale(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Address.getLocality", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.location.Address
            val wrapped: List<Any?> = try {
              listOf(api.getLocality(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Address.getLongitude", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.location.Address
            val wrapped: List<Any?> = try {
              listOf(api.getLongitude(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Address.getMaxAddressLineIndex", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.location.Address
            val wrapped: List<Any?> = try {
              listOf(api.getMaxAddressLineIndex(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Address.getPhone", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.location.Address
            val wrapped: List<Any?> = try {
              listOf(api.getPhone(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Address.getPostalCode", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.location.Address
            val wrapped: List<Any?> = try {
              listOf(api.getPostalCode(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Address.getPremises", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.location.Address
            val wrapped: List<Any?> = try {
              listOf(api.getPremises(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Address.getSubAdminArea", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.location.Address
            val wrapped: List<Any?> = try {
              listOf(api.getSubAdminArea(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Address.getSubLocality", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.location.Address
            val wrapped: List<Any?> = try {
              listOf(api.getSubLocality(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Address.getSubThouroughfare", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.location.Address
            val wrapped: List<Any?> = try {
              listOf(api.getSubThouroughfare(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Address.getThouroughfare", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.location.Address
            val wrapped: List<Any?> = try {
              listOf(api.getThouroughfare(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Address.getUrl", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.location.Address
            val wrapped: List<Any?> = try {
              listOf(api.getUrl(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Address.hasLatitude", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.location.Address
            val wrapped: List<Any?> = try {
              listOf(api.hasLatitude(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Address.hasLongitude", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.location.Address
            val wrapped: List<Any?> = try {
              listOf(api.hasLongitude(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  @Suppress("LocalVariableName", "FunctionName")
  /** Creates a Dart instance of Address and attaches it to [pigeon_instanceArg]. */
  fun pigeon_newInstance(pigeon_instanceArg: android.location.Address, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              AndroidGeocoderError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
    }     else if (pigeonRegistrar.instanceManager.containsInstance(pigeon_instanceArg)) {
      callback(Result.success(Unit))
    }     else {
      val pigeon_identifierArg = pigeonRegistrar.instanceManager.addHostCreatedInstance(pigeon_instanceArg)
      val binaryMessenger = pigeonRegistrar.binaryMessenger
      val codec = pigeonRegistrar.codec
      val channelName = "dev.flutter.pigeon.geocoding_android.Address.pigeon_newInstance"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(pigeon_identifierArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            callback(Result.failure(AndroidGeocoderError(it[0] as String, it[1] as String, it[2] as String?)))
          } else {
            callback(Result.success(Unit))
          }
        } else {
          callback(Result.failure(AndroidGeocoderLibraryPigeonUtils.createConnectionError(channelName)))
        } 
      }
    }
  }

}
/** Geographical bounds describing a geographic box. */
@Suppress("UNCHECKED_CAST")
abstract class PigeonApiGeographicBounds(open val pigeonRegistrar: AndroidGeocoderLibraryPigeonProxyApiRegistrar) {
  abstract fun pigeon_defaultConstructor(lowerLeftLatitude: Double, lowerLeftLongitude: Double, upperRightLatitude: Double, upperRightLongitude: Double): GeographicBounds

  abstract fun lowerLeftLatitude(pigeon_instance: GeographicBounds): Double

  abstract fun lowerLeftLongitude(pigeon_instance: GeographicBounds): Double

  abstract fun upperRightLatitude(pigeon_instance: GeographicBounds): Double

  abstract fun upperRightLongitude(pigeon_instance: GeographicBounds): Double

  companion object {
    @Suppress("LocalVariableName")
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, api: PigeonApiGeographicBounds?) {
      val codec = api?.pigeonRegistrar?.codec ?: AndroidGeocoderLibraryPigeonCodec()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.GeographicBounds.pigeon_defaultConstructor", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_identifierArg = args[0] as Long
            val lowerLeftLatitudeArg = args[1] as Double
            val lowerLeftLongitudeArg = args[2] as Double
            val upperRightLatitudeArg = args[3] as Double
            val upperRightLongitudeArg = args[4] as Double
            val wrapped: List<Any?> = try {
              api.pigeonRegistrar.instanceManager.addDartCreatedInstance(api.pigeon_defaultConstructor(lowerLeftLatitudeArg,lowerLeftLongitudeArg,upperRightLatitudeArg,upperRightLongitudeArg), pigeon_identifierArg)
              listOf(null)
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  @Suppress("LocalVariableName", "FunctionName")
  /** Creates a Dart instance of GeographicBounds and attaches it to [pigeon_instanceArg]. */
  fun pigeon_newInstance(pigeon_instanceArg: GeographicBounds, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              AndroidGeocoderError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
    }     else if (pigeonRegistrar.instanceManager.containsInstance(pigeon_instanceArg)) {
      callback(Result.success(Unit))
    }     else {
      val pigeon_identifierArg = pigeonRegistrar.instanceManager.addHostCreatedInstance(pigeon_instanceArg)
      val lowerLeftLatitudeArg = lowerLeftLatitude(pigeon_instanceArg)
      val lowerLeftLongitudeArg = lowerLeftLongitude(pigeon_instanceArg)
      val upperRightLatitudeArg = upperRightLatitude(pigeon_instanceArg)
      val upperRightLongitudeArg = upperRightLongitude(pigeon_instanceArg)
      val binaryMessenger = pigeonRegistrar.binaryMessenger
      val codec = pigeonRegistrar.codec
      val channelName = "dev.flutter.pigeon.geocoding_android.GeographicBounds.pigeon_newInstance"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(pigeon_identifierArg, lowerLeftLatitudeArg, lowerLeftLongitudeArg, upperRightLatitudeArg, upperRightLongitudeArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            callback(Result.failure(AndroidGeocoderError(it[0] as String, it[1] as String, it[2] as String?)))
          } else {
            callback(Result.success(Unit))
          }
        } else {
          callback(Result.failure(AndroidGeocoderLibraryPigeonUtils.createConnectionError(channelName)))
        } 
      }
    }
  }

}
/** Information about the current Android build, extracted from system properties. */
@Suppress("UNCHECKED_CAST")
abstract class PigeonApiBuild(open val pigeonRegistrar: AndroidGeocoderLibraryPigeonProxyApiRegistrar) {
  /** Returns the current Android SDK version that is running on the device. */
  abstract fun getSdkVersion(): Long

  companion object {
    @Suppress("LocalVariableName")
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, api: PigeonApiBuild?) {
      val codec = api?.pigeonRegistrar?.codec ?: AndroidGeocoderLibraryPigeonCodec()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Build.getSdkVersion", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getSdkVersion())
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  @Suppress("LocalVariableName", "FunctionName")
  /** Creates a Dart instance of Build and attaches it to [pigeon_instanceArg]. */
  fun pigeon_newInstance(pigeon_instanceArg: android.os.Build, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              AndroidGeocoderError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
    }     else if (pigeonRegistrar.instanceManager.containsInstance(pigeon_instanceArg)) {
      callback(Result.success(Unit))
    }     else {
      val pigeon_identifierArg = pigeonRegistrar.instanceManager.addHostCreatedInstance(pigeon_instanceArg)
      val binaryMessenger = pigeonRegistrar.binaryMessenger
      val codec = pigeonRegistrar.codec
      val channelName = "dev.flutter.pigeon.geocoding_android.Build.pigeon_newInstance"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(pigeon_identifierArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            callback(Result.failure(AndroidGeocoderError(it[0] as String, it[1] as String, it[2] as String?)))
          } else {
            callback(Result.success(Unit))
          }
        } else {
          callback(Result.failure(AndroidGeocoderLibraryPigeonUtils.createConnectionError(channelName)))
        } 
      }
    }
  }

}
/**
 * A listener for asynchronous geocoding results. Only one of the methods will
 * ever be invoked per geocoding attempt. There are no guarantees on how long
 * it will take for a method to be invoked, nor any guarantees on the format or
 * availability of error information.
 *
 * See https://developer.android.com/reference/android/location/Geocoder.GeocodeListener.
 */
@Suppress("UNCHECKED_CAST")
abstract class PigeonApiGeocodeListener(open val pigeonRegistrar: AndroidGeocoderLibraryPigeonProxyApiRegistrar) {
  @androidx.annotation.RequiresApi(api = 33)
  abstract fun pigeon_defaultConstructor(): android.location.Geocoder.GeocodeListener

  companion object {
    @Suppress("LocalVariableName")
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, api: PigeonApiGeocodeListener?) {
      val codec = api?.pigeonRegistrar?.codec ?: AndroidGeocoderLibraryPigeonCodec()
      if (android.os.Build.VERSION.SDK_INT >= 33) {
        run {
          val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.GeocodeListener.pigeon_defaultConstructor", codec)
          if (api != null) {
            channel.setMessageHandler { message, reply ->
              val args = message as List<Any?>
              val pigeon_identifierArg = args[0] as Long
              val wrapped: List<Any?> = try {
                api.pigeonRegistrar.instanceManager.addDartCreatedInstance(api.pigeon_defaultConstructor(), pigeon_identifierArg)
                listOf(null)
              } catch (exception: Throwable) {
                AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          } else {
            channel.setMessageHandler(null)
          }
        }
      }       else {
        val channel = BasicMessageChannel<Any?>(
          binaryMessenger,
          "dev.flutter.pigeon.geocoding_android.GeocodeListener.pigeon_defaultConstructor",
          codec
        )
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            reply.reply(AndroidGeocoderLibraryPigeonUtils.wrapError(UnsupportedOperationException(
              "Call references class `android.location.Geocoder.GeocodeListener`, which requires api version 33."
            )))
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  @Suppress("LocalVariableName", "FunctionName")
  /** Creates a Dart instance of GeocodeListener and attaches it to [pigeon_instanceArg]. */
  @androidx.annotation.RequiresApi(api = 33)
  fun pigeon_newInstance(pigeon_instanceArg: android.location.Geocoder.GeocodeListener, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              AndroidGeocoderError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
    }     else if (pigeonRegistrar.instanceManager.containsInstance(pigeon_instanceArg)) {
      callback(Result.success(Unit))
    }     else {
      callback(
          Result.failure(
              AndroidGeocoderError("new-instance-error", "Attempting to create a new Dart instance of GeocodeListener, but the class has a nonnull callback method.", "")))
    }
  }

  @androidx.annotation.RequiresApi(api = 33)
  fun onError(pigeon_instanceArg: android.location.Geocoder.GeocodeListener, errorMessageArg: String?, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              AndroidGeocoderError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
      return
    }
    val binaryMessenger = pigeonRegistrar.binaryMessenger
    val codec = pigeonRegistrar.codec
    val channelName = "dev.flutter.pigeon.geocoding_android.GeocodeListener.onError"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(pigeon_instanceArg, errorMessageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(AndroidGeocoderError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(AndroidGeocoderLibraryPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }

  @androidx.annotation.RequiresApi(api = 33)
  fun onGeocode(pigeon_instanceArg: android.location.Geocoder.GeocodeListener, addressesArg: List<android.location.Address?>, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              AndroidGeocoderError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
      return
    }
    val binaryMessenger = pigeonRegistrar.binaryMessenger
    val codec = pigeonRegistrar.codec
    val channelName = "dev.flutter.pigeon.geocoding_android.GeocodeListener.onGeocode"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(pigeon_instanceArg, addressesArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(AndroidGeocoderError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(AndroidGeocoderLibraryPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }

}
/**
 * A class for handling geocoding and reverse geocoding.
 *
 * See https://developer.android.com/reference/android/location/Geocoder.
 */
@Suppress("UNCHECKED_CAST")
abstract class PigeonApiGeocoder(open val pigeonRegistrar: AndroidGeocoderLibraryPigeonProxyApiRegistrar) {
  /** Creates a [Geocoder]. */
  abstract fun pigeon_defaultConstructor(locale: java.util.Locale?): android.location.Geocoder

  /**
   * Provides an array of Addresses that attempt to describe the area
   * immediately surrounding the given latitude and longitude.
   */
  @androidx.annotation.RequiresApi(api = 33)
  abstract fun getFromLocation(pigeon_instance: android.location.Geocoder, latitude: Double, longitude: Double, maxResults: Long, listener: android.location.Geocoder.GeocodeListener)

  /**
   * Provides an array of Addresses that attempt to describe the area
   * immediately surrounding the given latitude and longitude.
   *
   * Note: this method has been deprecated in Android API 33 as it can result
   * in blocking the main thread. On Android devices running API 33 or higher
   * please use the [Geocoder.getFromLocation] method.
   */
  abstract fun getFromLocationPreAndroidApi33(pigeon_instance: android.location.Geocoder, latitude: Double, longitude: Double, maxResults: Long): List<android.location.Address?>?

  /**
   * Returns an array of Addresses that attempt to describe the named location,
   * which may be a place name such as "Dalvik, Iceland", an address such as
   * "1600 Amphitheatre Parkway, Mountain View, CA", an airport code such as
   * "SFO", and so forth.
   *
   * Additional [bounds] can be specified to describe a geographical box
   * to which the search area will be limited.
   */
  @androidx.annotation.RequiresApi(api = 33)
  abstract fun getFromLocationName(pigeon_instance: android.location.Geocoder, locationName: String, maxResults: Long, listener: android.location.Geocoder.GeocodeListener, bounds: GeographicBounds?)

  /**
   * Returns an array of Addresses that attempt to describe the named location,
   * which may be a place name such as "Dalvik, Iceland", an address such as
   * "1600 Amphitheatre Parkway, Mountain View, CA", an airport code such as
   * "SFO", and so forth.
   *
   * Additional [bounds] can be specified to describe a geographical box
   * to which the search area will be limited.
   *
   * Note: this method has been deprecated in Android API 33 as it can result
   * in blocking the main thread. On Android devices running API 33 or higher
   * please use the [Geocoder.getFromLocation] method.
   */
  abstract fun getFromLocationNamePreAndroidApi33(pigeon_instance: android.location.Geocoder, locationName: String, maxResults: Long, bounds: GeographicBounds?): List<android.location.Address?>?

  /**
   * Returns true if there is a geocoder implementation present on the device
   * that may return results.
   */
  abstract fun isPresent(): Boolean

  companion object {
    @Suppress("LocalVariableName")
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, api: PigeonApiGeocoder?) {
      val codec = api?.pigeonRegistrar?.codec ?: AndroidGeocoderLibraryPigeonCodec()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Geocoder.pigeon_defaultConstructor", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_identifierArg = args[0] as Long
            val localeArg = args[1] as java.util.Locale?
            val wrapped: List<Any?> = try {
              api.pigeonRegistrar.instanceManager.addDartCreatedInstance(api.pigeon_defaultConstructor(localeArg), pigeon_identifierArg)
              listOf(null)
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      if (android.os.Build.VERSION.SDK_INT >= 33) {
        run {
          val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Geocoder.getFromLocation", codec)
          if (api != null) {
            channel.setMessageHandler { message, reply ->
              val args = message as List<Any?>
              val pigeon_instanceArg = args[0] as android.location.Geocoder
              val latitudeArg = args[1] as Double
              val longitudeArg = args[2] as Double
              val maxResultsArg = args[3] as Long
              val listenerArg = args[4] as android.location.Geocoder.GeocodeListener
              val wrapped: List<Any?> = try {
                api.getFromLocation(pigeon_instanceArg, latitudeArg, longitudeArg, maxResultsArg, listenerArg)
                listOf(null)
              } catch (exception: Throwable) {
                AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          } else {
            channel.setMessageHandler(null)
          }
        }
      }       else {
        val channel = BasicMessageChannel<Any?>(
          binaryMessenger,
          "dev.flutter.pigeon.geocoding_android.Geocoder.getFromLocation",
          codec
        )
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            reply.reply(AndroidGeocoderLibraryPigeonUtils.wrapError(UnsupportedOperationException(
              "Call references class `android.location.Geocoder.GeocodeListener`, which requires api version 33."
            )))
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Geocoder.getFromLocationPreAndroidApi33", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.location.Geocoder
            val latitudeArg = args[1] as Double
            val longitudeArg = args[2] as Double
            val maxResultsArg = args[3] as Long
            val wrapped: List<Any?> = try {
              listOf(api.getFromLocationPreAndroidApi33(pigeon_instanceArg, latitudeArg, longitudeArg, maxResultsArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      if (android.os.Build.VERSION.SDK_INT >= 33) {
        run {
          val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Geocoder.getFromLocationName", codec)
          if (api != null) {
            channel.setMessageHandler { message, reply ->
              val args = message as List<Any?>
              val pigeon_instanceArg = args[0] as android.location.Geocoder
              val locationNameArg = args[1] as String
              val maxResultsArg = args[2] as Long
              val listenerArg = args[3] as android.location.Geocoder.GeocodeListener
              val boundsArg = args[4] as GeographicBounds?
              val wrapped: List<Any?> = try {
                api.getFromLocationName(pigeon_instanceArg, locationNameArg, maxResultsArg, listenerArg, boundsArg)
                listOf(null)
              } catch (exception: Throwable) {
                AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          } else {
            channel.setMessageHandler(null)
          }
        }
      }       else {
        val channel = BasicMessageChannel<Any?>(
          binaryMessenger,
          "dev.flutter.pigeon.geocoding_android.Geocoder.getFromLocationName",
          codec
        )
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            reply.reply(AndroidGeocoderLibraryPigeonUtils.wrapError(UnsupportedOperationException(
              "Call references class `android.location.Geocoder.GeocodeListener`, which requires api version 33."
            )))
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Geocoder.getFromLocationNamePreAndroidApi33", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as android.location.Geocoder
            val locationNameArg = args[1] as String
            val maxResultsArg = args[2] as Long
            val boundsArg = args[3] as GeographicBounds?
            val wrapped: List<Any?> = try {
              listOf(api.getFromLocationNamePreAndroidApi33(pigeon_instanceArg, locationNameArg, maxResultsArg, boundsArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Geocoder.isPresent", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isPresent())
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  @Suppress("LocalVariableName", "FunctionName")
  /** Creates a Dart instance of Geocoder and attaches it to [pigeon_instanceArg]. */
  fun pigeon_newInstance(pigeon_instanceArg: android.location.Geocoder, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              AndroidGeocoderError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
    }     else if (pigeonRegistrar.instanceManager.containsInstance(pigeon_instanceArg)) {
      callback(Result.success(Unit))
    }     else {
      val pigeon_identifierArg = pigeonRegistrar.instanceManager.addHostCreatedInstance(pigeon_instanceArg)
      val binaryMessenger = pigeonRegistrar.binaryMessenger
      val codec = pigeonRegistrar.codec
      val channelName = "dev.flutter.pigeon.geocoding_android.Geocoder.pigeon_newInstance"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(pigeon_identifierArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            callback(Result.failure(AndroidGeocoderError(it[0] as String, it[1] as String, it[2] as String?)))
          } else {
            callback(Result.success(Unit))
          }
        } else {
          callback(Result.failure(AndroidGeocoderLibraryPigeonUtils.createConnectionError(channelName)))
        } 
      }
    }
  }

}
/**
 * A `Locale` object represents a specific geographical, political, or cultural
 * region.
 *
 * See https://developer.android.com/reference/java/util/Locale.
 */
@Suppress("UNCHECKED_CAST")
abstract class PigeonApiLocale(open val pigeonRegistrar: AndroidGeocoderLibraryPigeonProxyApiRegistrar) {
  /** Creates a [Locale]. */
  abstract fun pigeon_defaultConstructor(identifier: String): java.util.Locale

  /**
   * Returns the country/region code for this locale, which should either be
   * the empty string, an uppercase ISO 3166 2-letter code, or a UN M.49
   * 3-digit code.
   */
  abstract fun getCountry(pigeon_instance: java.util.Locale): String

  /**
   * If the country matches an ISO 3166-1 alpha-2 code, the corresponding
   * ISO 3166-1 alpha-3 uppercase code is returned.
   */
  abstract fun getISO3Country(pigeon_instance: java.util.Locale): String

  /**
   * If the language matches an ISO 639-1 two-letter code, the corresponding
   * ISO 639-2/T three-letter lowercase code is returned.
   */
  abstract fun getISO3Language(pigeon_instance: java.util.Locale): String

  /** Returns the language code of this Locale. */
  abstract fun getLanguage(pigeon_instance: java.util.Locale): String

  /**
   * Returns the script for this locale, which should either be the empty
   * string or an ISO 15924 4-letter script code.
   */
  abstract fun getScript(pigeon_instance: java.util.Locale): String

  /** Returns the variant code for this locale. */
  abstract fun getVariant(pigeon_instance: java.util.Locale): String

  companion object {
    @Suppress("LocalVariableName")
    fun setUpMessageHandlers(binaryMessenger: BinaryMessenger, api: PigeonApiLocale?) {
      val codec = api?.pigeonRegistrar?.codec ?: AndroidGeocoderLibraryPigeonCodec()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Locale.pigeon_defaultConstructor", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_identifierArg = args[0] as Long
            val identifierArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.pigeonRegistrar.instanceManager.addDartCreatedInstance(api.pigeon_defaultConstructor(identifierArg), pigeon_identifierArg)
              listOf(null)
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Locale.getCountry", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as java.util.Locale
            val wrapped: List<Any?> = try {
              listOf(api.getCountry(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Locale.getISO3Country", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as java.util.Locale
            val wrapped: List<Any?> = try {
              listOf(api.getISO3Country(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Locale.getISO3Language", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as java.util.Locale
            val wrapped: List<Any?> = try {
              listOf(api.getISO3Language(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Locale.getLanguage", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as java.util.Locale
            val wrapped: List<Any?> = try {
              listOf(api.getLanguage(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Locale.getScript", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as java.util.Locale
            val wrapped: List<Any?> = try {
              listOf(api.getScript(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.geocoding_android.Locale.getVariant", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pigeon_instanceArg = args[0] as java.util.Locale
            val wrapped: List<Any?> = try {
              listOf(api.getVariant(pigeon_instanceArg))
            } catch (exception: Throwable) {
              AndroidGeocoderLibraryPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }

  @Suppress("LocalVariableName", "FunctionName")
  /** Creates a Dart instance of Locale and attaches it to [pigeon_instanceArg]. */
  fun pigeon_newInstance(pigeon_instanceArg: java.util.Locale, callback: (Result<Unit>) -> Unit)
{
    if (pigeonRegistrar.ignoreCallsToDart) {
      callback(
          Result.failure(
              AndroidGeocoderError("ignore-calls-error", "Calls to Dart are being ignored.", "")))
    }     else if (pigeonRegistrar.instanceManager.containsInstance(pigeon_instanceArg)) {
      callback(Result.success(Unit))
    }     else {
      val pigeon_identifierArg = pigeonRegistrar.instanceManager.addHostCreatedInstance(pigeon_instanceArg)
      val binaryMessenger = pigeonRegistrar.binaryMessenger
      val codec = pigeonRegistrar.codec
      val channelName = "dev.flutter.pigeon.geocoding_android.Locale.pigeon_newInstance"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(pigeon_identifierArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            callback(Result.failure(AndroidGeocoderError(it[0] as String, it[1] as String, it[2] as String?)))
          } else {
            callback(Result.success(Unit))
          }
        } else {
          callback(Result.failure(AndroidGeocoderLibraryPigeonUtils.createConnectionError(channelName)))
        } 
      }
    }
  }

}
